# Generated by Django 4.0.1 on 2022-01-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
