# Generated by Django 4.0.1 on 2022-02-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_venta_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='stado',
            field=models.BooleanField(default=False),
        ),
    ]
