# Generated by Django 4.0.1 on 2022-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_venta_stado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='subtotal',
            field=models.IntegerField(default=0.0),
        ),
    ]
