# Generated by Django 4.0.1 on 2022-02-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_detsale_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
