# Generated by Django 4.0.1 on 2022-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_venta_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='mail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='rut',
            field=models.CharField(default='', max_length=30),
        ),
    ]
