# Generated by Django 4.0.1 on 2022-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_clientes_mail_clientes_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='rut',
            field=models.CharField(default='Consumidor Final', max_length=30),
        ),
    ]
